INSERT INTO tags (slug, name_ru, name_en) VALUES
  ('adventure',                    'приключения',                   'Adventure'),
  ('fantasy',                      'фэнтези',                       'Fantasy'),
  ('science-fiction',              'фантастика',                    'Science Fiction'),
  ('short-story',                  'рассказ',                       'Short Story'),
  ('magic',                        'магия',                         'Magic'),
  ('love',                         'любовь',                        'Love'),
  ('original-world',               'авторский мир',                 'Original World'),
  ('humor',                        'юмор',                          'Humor'),
  ('mystery',                      'мистика',                       'Mystery'),
  ('isekai',                       'исекай',                     'Isekai'),
  ('drama',                        'драма',                         'Drama'),
  ('romance',                      'романтика',                     'Romance'),
  ('philosophy',                   'философия',                     'Philosophy'),
  ('friendship',                   'дружба',                        'Friendship'),
  ('magical-world',                'магический мир',                'Magical World'),
  ('superpowers',                  'сверхспособности',              'Superpowers'),
  ('war',                          'война',                         'War'),
  ('horror',                       'ужасы',                         'Horror'),
  ('modern-day',                   'современность',                 'Modern Day'),
  ('post-apocalyptic',             'постапокалипсис',               'Post-Apocalyptic'),
  ('fairy-tale',                   'сказка',                        'Fairy Tale'),
  ('space',                        'космос',                        'Space'),
  ('future',                       'будущее',                       'Future'),
  ('military-sci-fi',              'боевая фантастика',             'Military Sci-Fi'),
  ('psychology',                   'психология',                    'Psychology'),
  ('survival',                     'выживание',                     'Survival'),
  ('alternate-history',            'альтернативная история',        'Alternate History'),
  ('other-worlds',                 'иные миры',                     'Other Worlds'),
  ('action',                       'боевик',                        'Action'),
  ('detective',                    'детектив',                      'Detective'),
  ('demons',                       'демоны',                        'Demons'),
  ('social-sci-fi',                'социальная фантастика',         'Social Sci-Fi'),
  ('erotica',                      'эротика',                       'Erotica'),
  ('thriller',                     'триллер',                       'Thriller'),
  ('prose',                        'проза',                         'Prose'),
  ('realrpg',                      'реалрпг',                       'RealRPG'),
  ('humor-and-irony',              'юмор и ирония',                 'Humor and Irony'),
  ('dark-fantasy',                 'темное фэнтези',                'Dark Fantasy'),
  ('monsters',                     'монстры',                       'Monsters'),
  ('space-sci-fi',                 'космическая фантастика',        'Space Sci-Fi'),
  ('alternate-reality',            'альтернативная реальность',     'Alternate Reality'),
  ('relationships',                'отношения',                     'Relationships'),
  ('dragons',                      'драконы',                       'Dragons'),
  ('history',                      'история',                       'History'),
  ('enemies-to-lovers',            'от ненависти до любви',         'Enemies to Lovers'),
  ('science-fiction-2',            'научная фантастика',            'Science Fiction'),
  ('vampires',                     'вампиры',                       'Vampires'),
  ('intrigue',                     'интриги',                       'Intrigue'),
  ('werewolves',                   'оборотни',                      'Werewolves / Shapeshifters'),
  ('dystopia',                     'антиутопия',                    'Dystopia'),
  ('realism',                      'реализм',                       'Realism'),
  ('dangerous-adventures',         'опасные приключения',           'Dangerous Adventures'),
  ('cyberpunk',                    'киберпанк',                     'Cyberpunk'),
  ('gods',                         'боги',                          'Gods'),
  ('slice-of-life',                'повседневность',                'Slice of Life'),
  ('complicated-relationships',    'сложные отношения',             'Complicated Relationships'),
  ('family',                       'семья',                         'Family'),
  ('first-love',                   'первая любовь',                 'First Love'),
  ('mythical-creatures',           'мифические существа',           'Mythical Creatures'),
  ('another-world',                'другой мир',                    'Another World'),
  ('zombies',                      'зомби',                         'Zombies'),
  ('original-races',               'авторские расы',                'Original Races')
ON DUPLICATE KEY UPDATE
  name_ru = VALUES(name_ru),
  name_en = VALUES(name_en);